name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install
      run: cd hello_world && npm install
    - name: pip --version
      run: pip --version
    - name: install SCF CLI
      run: sudo pip install scf
    - name: scf configure
      env: 
        APPID: 1252618971
        REGION: ap-guangzhou
        SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
      run: scf configure set --appid $APPID --region $REGION --secret-id $SECRET_ID --secret-key $SECRET_KEY
    - name: scf deploy
      run: scf deploy -t ./hello_world/template.yaml -f
  
